describe('Login Scripts', () => {
    beforeEach(function(){
        cy.visit('HomePageAddress')
        // cy.get('HomePageElement')
        // cy.get('HomePageElement')
        cy.url().should('eq', 'HomePageAddress')
        cy.viewport(1920, 1000)
    })
    
// Mobile Responsiveness
    
    it('Mobile Responsiveness Portrait', () => {
        cy.viewport('macbook-15')
        cy.ScrollUI()
        cy.viewport('macbook-13')
        cy.ScrollUI()
        cy.viewport('macbook-11')
        cy.ScrollUI()
        cy.viewport('ipad-2')
        cy.ScrollUI()
        cy.viewport('ipad-mini')
        cy.ScrollUI()
        cy.viewport('iphone-6+')
        cy.ScrollUI()
        cy.viewport('iphone-6')
        cy.ScrollUI()
        cy.viewport('iphone-5')
        cy.ScrollUI()
        cy.viewport('iphone-4')
        cy.ScrollUI()
        cy.viewport('iphone-3')
        cy.ScrollUI()
        cy.viewport(2000, 1250)
        cy.ScrollUI()
    })

    it('Mobile Responsiveness Landscape', () => {
        cy.viewport('macbook-15', 'landscape')
        cy.wait(1500)
        cy.viewport('macbook-15', 'landscape')
        cy.wait(2000)
        cy.viewport('macbook-13', 'landscape')
        cy.ScrollUI()
        cy.viewport('macbook-11', 'landscape')
        cy.ScrollUI()
        cy.viewport('ipad-2', 'landscape')
        cy.ScrollUI()
        cy.viewport('ipad-mini', 'landscape')
        cy.ScrollUI()
        cy.viewport('iphone-6+', 'landscape')
        cy.ScrollUI()
        cy.viewport('iphone-6', 'landscape')
        cy.ScrollUI()
        cy.viewport('iphone-5', 'landscape')
        cy.ScrollUI()
        cy.viewport('iphone-4', 'landscape')
        cy.ScrollUI()
        cy.viewport('iphone-3', 'landscape')
        cy.ScrollUI()
        cy.viewport(2000, 1250)
        cy.ScrollUI()
    })

//     Sign-In Button    
    it('Sign-In Button', function(){
        cy.get('signInButtonElement').click()
        cy.get('loginPageElement1')
        cy.get('loginPageElement1')
        cy.url().should('contains', 'uniqueWebAdressText')
    })

//   HomePage Logo
    it('LandingPage Logo', () => {
        cy.get('logoElement').click()
        cy.get('HomePageElement')
        cy.get('HomePageElement')
        cy.url().should('eq', 'HomePageAddress')
    })
})
